# fly.toml app configuration file generated for python-tutorial-holy-feather-691 on 2024-08-22T23:20:30+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'python-tutorial-holy-feather-691'
primary_region = 'otp'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
